services:
  psql-db:
    image: postgres
    container_name: postgresql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=BookStoreApplication
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'

  bookstore:
    container_name: bookstore
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=BookStoreApplication
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgresql